"""Build courses/STAGE2_REVIEW.md: every Review Flag from Stage 2, grouped by course and tag."""

import json
import re

from check_content import sections
from check_curriculum import CATALOG, ROOT, slug_for

TAGS = ["VERIFY", "VERSION", "REGION"]


def main():
    briefs = json.loads(CATALOG.read_text())
    rows, body = [], []
    totals = {"lessons": 0, "words": 0, **{t: 0 for t in TAGS}, "signoff": 0}
    for b in briefs:
        d = ROOT / "courses" / slug_for(b)
        c = json.loads((d / "curriculum.json").read_text())
        lessons = [lesson for m in c["modules"] for lesson in m["lessons"]]
        counts = {t: 0 for t in TAGS}
        signoff = 0
        words = []
        items = []
        for lesson in lessons:
            text = (d / "lessons" / lesson["lesson_id"] / "content.md").read_text()
            words.append(len(re.findall(r"\w+", text)))
            for line in sections(text)["Review Flags"].strip().splitlines():
                line = line.strip().lstrip("- ").strip()
                if not line or line.lower().startswith("none"):
                    continue
                for t in TAGS:
                    if f"[{t}]" in line:
                        counts[t] += 1
                if "sign-off" in line.lower():
                    signoff += 1
                items.append(f"- **{lesson['lesson_id']}** {line}")
        totals["lessons"] += len(lessons)
        totals["words"] += sum(words)
        totals["signoff"] += signoff
        for t in TAGS:
            totals[t] += counts[t]
        rows.append(f"| {b['course_id']} | {c['course_title']} | {len(lessons)} | {min(words)}–{max(words)} | "
                    f"{counts['VERIFY']} | {counts['VERSION']} | {counts['REGION']} | {signoff or ''} |")
        body.append(f"## {b['course_id']}: {c['course_title']}\n\n" + ("\n".join(items) or "- No flags.") + "\n")
    head = [
        "# CertifAI Stage 2 review",
        "",
        f"30 courses · {totals['lessons']} lessons · {totals['words']:,} words · "
        f"{totals['VERIFY']} [VERIFY] · {totals['VERSION']} [VERSION] · {totals['REGION']} [REGION] · "
        f"{totals['signoff']} sign-off lines",
        "",
        "Generated by `courseforge/stage2_review.py` from each lesson's Review Flags. [VERIFY] means a fact "
        "to check, [VERSION] means tool details to confirm against the live tool before recording, and "
        "[REGION] means country-specific.",
        "",
        "| ID | Course | Lessons | Words per lesson | VERIFY | VERSION | REGION | Sign-off |",
        "|---|---|---|---|---|---|---|---|",
    ]
    (ROOT / "courses" / "STAGE2_REVIEW.md").write_text("\n".join(head + rows) + "\n\n" + "\n".join(body))
    print(totals)


if __name__ == "__main__":
    main()
