"""Build courses/STAGE1_REVIEW.md: one page to approve every Stage 1 curriculum."""

import json
import re
from pathlib import Path

from check_curriculum import CATALOG, ROOT, slug_for

PROPOSED = re.compile(r"PROPOSED:? screen demos? for ((?:L\d{2}[, ]*(?:and )?)+)")


def proposed_demos(flags):
    found = []
    for f in flags:
        if m := PROPOSED.search(f):
            found += re.findall(r"L\d{2}", m.group(1))
    return sorted(set(found))


def main():
    briefs = json.loads(CATALOG.read_text())
    rows, sections = [], []
    totals = {"lessons": 0, "minutes": 0, "demos": 0, "proposed": 0}
    for b in briefs:
        c = json.loads((ROOT / "courses" / slug_for(b) / "curriculum.json").read_text())
        lessons = [lesson for m in c["modules"] for lesson in m["lessons"]]
        demos, proposed = c["screen_demo_lessons"], proposed_demos(c["flags"])
        blockers = [f for f in c["flags"] if "BLOCKER" in f.upper() or "must sign off" in f.lower()]
        totals["lessons"] += len(lessons)
        totals["minutes"] += c["time_plan"]["video_minutes"]
        totals["demos"] += len(demos)
        totals["proposed"] += len(proposed)
        rows.append(f"| {b['course_id']} | {b['track']} | {c['course_title']} | {len(lessons)} | "
                    f"{c['status'].replace('_', ' ').title()} | {len(demos)} | "
                    f"{', '.join(proposed) or '-'} | {'Yes' if blockers else ''} |")
        s = [f"## {b['course_id']}: {c['course_title']}",
             "", f"{b['level']} · {b['track']} · {len(lessons)} lessons · "
             f"{c['time_plan']['video_minutes']} min of video · status **{c['status']}**", "",
             "**Objectives**", ""]
        s += [f"- {o['id']} ({o['bloom']}): {o['text']}" for o in c["objectives"]]
        s += ["", "**Modules**", ""]
        for m in c["modules"]:
            s.append(f"- **{m['module_id']} {m['title']}**: " +
                     "; ".join(f"{lesson['lesson_id']} {lesson['title']}" for lesson in m["lessons"]))
        s += ["", f"**Capstone** ({', '.join(c['capstone'].get('built_in', []))}): "
              f"{c['capstone'].get('brief') or b['capstone_project']}", ""]
        if demos:
            s.append(f"**Screen demos:** {', '.join(demos)}")
        if proposed:
            s.append(f"**Proposed screen demos (need approval):** {', '.join(proposed)}")
        s += ["", "**Flags**", ""] + [f"- {f}" for f in c["flags"]] + [""]
        sections.append("\n".join(s))
    head = [
        "# CertifAI Stage 1 review",
        "",
        f"{len(briefs)} courses · {totals['lessons']} lessons · {totals['minutes'] / 60:.1f} hours of video · "
        f"{totals['demos']} screen demos in the curricula · {totals['proposed']} more proposed",
        "",
        "Generated by `courseforge/stage1_review.py`. Tags in the flags: [VERIFY] means a fact to check, "
        "[VERSION] means tool details that change often, [REGION] means country-specific.",
        "",
        "| ID | Track | Course | Lessons | Status | Screen demos | Proposed demos | Release blocker |",
        "|---|---|---|---|---|---|---|---|",
    ]
    out = ROOT / "courses" / "STAGE1_REVIEW.md"
    out.write_text("\n".join(head + rows) + "\n\n" + "\n".join(sections))
    print(f"wrote {out.relative_to(ROOT.parent)}: {totals}")


if __name__ == "__main__":
    main()
