"""Build courses/STAGE3_REVIEW.md: Stage 3 totals and the recording/production load per course."""

import json
from collections import Counter

from check_curriculum import CATALOG, ROOT, slug_for


def main():
    rows, notes_md = [], []
    tot = Counter()
    for b in json.loads(CATALOG.read_text()):
        d = ROOT / "courses" / slug_for(b)
        c = json.loads((d / "curriculum.json").read_text())
        lessons = [lesson["lesson_id"] for m in c["modules"] for lesson in m["lessons"]]
        k = Counter()
        secs = 0.0
        hero = []
        for lid in lessons:
            sl = json.loads((d / "lessons" / lid / "shotlist.json").read_text())
            secs += sl["duration_s"]
            for s in sl["scenes"]:
                k[s["visual_type"]] += 1
                if s["visual_type"] == "hero_broll":
                    hero.append(f"{lid}/{s['scene']} [{s['broll_tool']}]")
        tot.update(k)
        tot["lessons"] += len(lessons)
        tot["seconds"] += secs
        rows.append(f"| {b['course_id']} | {c['course_title']} | {len(lessons)} | {secs / 60:.0f} | "
                    f"{k['slide']} | {k['stock']} | {k['screen']} | {k['hero_broll']} | {k['text']} |")
        if hero:
            notes_md.append(f"- **{b['course_id']}**: " + ", ".join(hero))
    head = [
        "# CertifAI Stage 3 review",
        "",
        f"30 courses · {tot['lessons']} lessons · {tot['seconds'] / 3600:.1f} hours of narration · "
        f"{tot['slide']} slides · {tot['stock']} stock shots · {tot['screen']} screen-recording scenes · "
        f"{tot['hero_broll']} hero B-roll clips · {tot['text']} text cards",
        "",
        "Generated by `courseforge/stage3_review.py` from every lesson's `shotlist.json`. Each lesson's "
        "`script.md` holds the narration to paste into HeyGen, and its Production Notes list what to check "
        "before recording.",
        "",
        "## Stage 4 workload per course",
        "",
        "| ID | Course | Lessons | Minutes | Slides | Stock | Screen | Hero B-roll | Text |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    tail = ["", "## Hero B-roll clips for the B-roll Pack (lesson/scene [tool])", ""] + notes_md + [
        "", f"At most 8 clips a day on free credits, so the {tot['hero_broll']} clips take about "
        f"{-(-tot['hero_broll'] // 8)} days of generation.", ""]
    (ROOT / "courses" / "STAGE3_REVIEW.md").write_text("\n".join(head + rows + tail))
    print({k: (round(v) if isinstance(v, float) else v) for k, v in tot.items()})


if __name__ == "__main__":
    main()
